### ISSUE TITLE
Order marked paid twice

### ISSUE THREAD

**Issue by stenvdb** [craftcms/commerce-mollie#23]
### Description
In our commerce shop we got an order that has been marked as paid twice (aka the double of the actual amount).

I have tried setting the `totalPaid` db column manually to the correct amount, but that doesn't show up in the CMS (caching?). Have sent an email about this to craft support, but have gotten no response since oct. 25th. So I'll try here.. The payment gateway is Mollie. Is there some kind of race condition that is not 100% bullet proof?

### Steps to reproduce

1.
2.

### Additional info

- Craft version: 3.3.6
- PHP version: 7.2
- Database driver & version:
- Plugins & versions: Commerce: 2.1.13, Mollie: 2.1.0.1

**Comment by nfourtythree** [comment]
Hi @stenvdb 

We have pushed an update to webhooks for mollie that could solve this issue.

I posted about how to [update to the pre-release](https://github.com/craftcms/commerce-mollie/issues/22#issuecomment-576170509) and asked for feedback to see if this helped with issues.

Would be great if you could see if this solves the problems you are seeing.

Thanks!

**Comment by stenvdb** [comment]
Hi @nfourtythree , will update asap, and wil let you know if this would happen again. Thanks!

Could you help me fix the issue above though? Changing the totalPaid column in the database, does not update in the cp. Can't figure this out.. We need to do something so the double paid amount gets fixed in the invoices etc.

**Comment by stenvdb** [comment]
@nfourtythree I have tracked down the issue to 2 records in the transaction table for the specific order, both marked as status 'success'. I assume the webhook fix in commerce-mollie 2.1.1. (https://github.com/craftcms/commerce-mollie/issues/22) prevents this from happening in the future.

For now (as I don't have time to update), I have set 1 of the 2 records as failed, making the totalPaid appear as it should.

As far as I'm concerned, this can be closed.

**Comment by nfourtythree** [comment]
Hi @stenvdb 

Thanks for the update!

**Comment by PieterxJan** [comment]
Hi guys,

I still have this issue in a project for a client of us. As Sten stated, there are two transaction records, created on the exact same time, with the `success` status. 

We have the latest version (2.1.1). I can fix this issue by setting the status manually, but the invoices are incorrect when they're generated because of this issue. 

This is all on a production environment. I can't seem to reproduce this on my local dev environment. 

### Additional info
- Craft version: 3.4.18
- PHP version: 7.2.30
- Craft Commerce version: 3.1.3

**Comment by stenvdb** [comment]
Hi @nfourtythree, unfortunately as @PieterxJan stated, I too have noticed that the issue is still not resolved. This is at least for our clients, a very critical bug. Because of this bug our client thought initially they sold way more than they actually did.

Of course logging in to mollie qiuckly shows you a correct sale amount. But because of this bug, for example the Commerce revenue dashboard widgets show a completely false overview of your shop sales. Very hard to explain to our clients.

If you want I can share a database dump, or even access to the site. Hopefully it can get fixed soon :crossed_fingers: Thanks for looking into this!

**Comment by stenvdb** [comment]
@brandonkelly @angrybrad Sorry to bug you on this ticket, but it has been 2 weeks without a reply. We have several shops running on Mollie and hope to get this fixed. 🙏

**Comment by nfourtythree** [comment]
Hi @stenvdb 

Thank you for emailing support, we have sent you a reply there. 

Just to keep everyone updated, this is something we are looking into and will update the issue when we have some information to share.

Will re-open this for visibility.

Thanks.

**Comment by alexthn** [comment]
Just to let you guys know, we also face this problem. For us it doesn't happen all the time but it does at least a couple of times a week.

**Comment by nfourtythree** [comment]
Hi All

Depending on what version of Commerce you are on we have just pushed `2.2.21` and `3.1.9`.

The appropriate release and version `2.1.2` should fix this issue. Please update and let us know how you get on.

Thanks for all of your help in tracking this down.

**Comment by stenvdb** [comment]
Thank you @nfourtythree! I will update our sites running on mollie today and keep an eye on it.
